### ISSUE TITLE
Comment on code results in error

### ISSUE THREAD

**Issue by hp-pepster** [omrisarig13/vim-mr-interface#41]
Hi,

thanks for your plugin. Unfortunately it does not completely work for me (might be a problem on my side). At the moment my company uses GitLab Community Edition 13.8.5.

MRInterfaceAddComment does work but adding comments on code lines does not. I edited the autoload/mr_interface.vim a little bit to get back the error. It's the same as if I try the generated curl-command directly in the command line. The result is always:
`{"message":"400 Bad request - Note {:line_code=\u003e[\"can't be blank\", \"must be a valid line code\"]}"}`
As can be seen [here](https://stackoverflow.com/questions/65926187/what-is-a-gitlab-line-code-as-referenced-when-creating-a-new-merge-request-threa) line_code should only be needed if you comment on multiple lines.

The feature to comment on multiple lines got added some time ago, maybe this is the problem.

Or maybe I just don't understand everything correctly. To get the base, start and head_sha I used the command from the gitlab doku [here](https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr)
`curl --request GET --header "PRIVATE-TOKEN: xxxx" https://example.com/api/v4/projects/nnnn/merge_requests/mmmm`

Despite beeing inside the repo and on the MR-Branches head the SHAs don't get calculated automatically. But I can use HEAD, HEAD~1 and so on. These SHAs are correct if I look at the curl command. Maybe I just understood the documentation wrong and this is the intended behaviour.

Tell me if you need more information.

**Comment by omrisarig13** [comment]
Hi @hp-pepster,

Thank you for creating this issue, I will try to look into it.

As far as I know, all the functionality of the plugin works (including adding comments on lines and getting the SHAs of the branches automatically), but I haven't tested/used the plugin in a while, so maybe some changes were made in GitLab. Anyway, it should be possible to solve your issues.

The feature of adding comments on multiple lines was added after I finished working on the plugin, in case the interface changed after they added this feature, it is possible that the plugin broke.

I will have time to look into this issue during the weekend, but a bit more information might help me:
- Versions of vim/nvim, git, and your machine (I don't think it is relevant to the comments as the curl line generated seems to be the problem, but it might be relevant to the SHAs error)
- The CURL command the code sends which results in bad request (without any private information of course).
- What type of files are you trying to add comments to (files that were added in the MR, files that were removed in the MR, or files that were just modified). If you can check if the bug appears in all these options this can be great (but not necessary as of now).
- Any flags you have configured for the plugin.

As of now, I only have access as a regular user to the public gitlab (gitlab.com), I hope I will be able to reproduce the bug there.

/ Omri

**Comment by hp-pepster** [comment]
Hi Omri,

thank you for you effords despite no longer using the plugin.

To answer your questions:
- Unfortunately I have to work on Windows10 at the moment so I used WSL2 and installed Ubuntu 20.04
- vim: VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
Included patches: 1-2269
- git version 2.25.1
- I also logged into my main Linux-PC with native UBuntu 20.04, VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 26 2020 13:21:11) Included patches: 1-1962 and Git 2.25.1
- CURL:
```bash
curl  -H "Content-Type: application/json" -d '{"position": {"new_line": 1, "start_sha": "origin/masters SHA", "old_path": "Src/test.c", "position_type": "text", "new_path": "Src/test.c", "base_sha": "origin/masters SHA", "head_sha": "HEADs SHA"}, "body": "Test"}' --request POST --header "PRIVATE-TOKEN:  " https://git01.mycompany.de/api/v4/projects/aaaa/merge_requests/bb/discussions?body=note
```


I tried different git scenarios:
- MR in a branch based on master
- MR in a branch based on another branch
- Comment on a new c-file
- Comment on a modified c-file on a new line
- Comment on a modified c-file on an old line

I removed all git-plugins exept the ones your plugin needs and I cleaned my vimrc exept some essential parameters. Here are the glaive-settings in my vimrc:
```vim
call glaive#Install()
Glaive mr-interface gitlab_private_token='xxx'
Glaive mr-interface gitlab_server_address='git01.mycompany.de'
Glaive mr-interface automatically_insert_cache
```

If you need anything else please let me know.

Thanks and have a nice weekend

**Comment by omrisarig13** [comment]
Hi @hp-pepster 

I run some tests on the plugin and it seems to continue to work as expected on my setup.
I think that what you have described regarding the SHA information is the expected behavior, and unfortunately, I could not reproduce your error when adding comments to the code.

### SHAs information:
- The plugin **should not** ask for SHA if you are on an MR branch and adds a general comment/discussion thread.
- The plugin **should** ask for SHA information if you are adding a comment on the code (regardless of whether you are on an MR branch or not). This is done to make it possible to add comments on SHAs which are in the middle of the MR, not necessarily the last and first commits. The SHAs should be requested only the first time you add a comment in the vim session.

Is this the behavior you are experiencing?
As you have noted, you can use any git reference (HEAD, branches names...).

### Adding comments on code

The parameters needed for adding comments on the code (and the error value returned) are very counter-intuitive.

I get the error you have mentioned in case I try to add a comment to an unchanged line in a modified file and don't provide both lines (old line and new line). From my experience, the same error is being returned for any issue in GitLab regarding missing or wrong information about the code location, regardless of what information is missing or wrong.
For the full information about the exact parameters you need to provide for every change type, you can have a look at [this table](https://github.com/omrisarig13/vim-mr-interface#how-to-add-new-code-discussion-thread).

In your CURL example, in case line number 1 was not changed in `Src/test.c` you should get this error. However, if the line was changed (or `Src/test.c` is a new file) your command should succeed.

It seems that the SHA values you are using are correct (for MR on master, when you are on the MR branch, `start_sha=master`, `base_sha=master`, `head_sha=HEAD` should work).

Can you try running the command with parameters for both new-line and old-line? Please make sure to add a comment to the same line (the easiest way to do it is to add a comment to the first line in a file with changes below). You will need to run the function `MRInterfaceAddCodeDiscussionThread` to provide these parameters.

If you can try to run the same scenario with a free user in `gitlab.com` repository that can also help to figure out where is the issue (as this is the only GitLab server I have access to as of now).

---

I have run the tests with the online GitLab, which is GitLab Enterprise Edition 13.12.0-pre. I think it is unlikely that the relevant merge request API is different between this server and the one you are using.



/ Omri

**Comment by hp-pepster** [comment]
Hi,

I might have found the error.
The behavior of the SHA calculation is as you described. I just misunderstood the documentation.

`MRInterfaceAddCodeDiscussionThread` and his brothers `MRInterfaceAddCodeDiscussionThreadOnOldCode` an `MRInterfaceAddCodeDiscussionThreadOnNewCode` are working. My problem was that I was too deep in the repo dir structure.

My repo path is like this: `repo_name/systems/system_name/project_name` so the path from you script was just `project_name/Src/test.c`. If I'm in the repo's root everything works flawless.

Thank you again for you time and work and sorry for the useless fuzz.

Maybe I can find some time to further enhance you very useful script, e.g. showing the comments from gitlab (and answering them) seems very interesting. But unfortunately I can't promise anything as we have a lot of work to do with little time for things outside of our projects.
